Feat/init
vtex-apps/search-page-context pull request #1
Opened 2019-08-21 13:53 UTC by jgfidelis

Create app.

This app is the search page context, contains three contexts.

One to pass down variables set by user in blocks (SearchPageContext). This way, the children in flex search-result can access it.

One context to hold variable state in search page, like if the search is loading, what mobile layout is selected, etc. (SearchPageStateContext)

One context that holds the dispatch function for the search page state context.

2019-08-21 14:43 UTC, iaronaraujo requested changes
Small addition to readme

2019-08-21 14:43 UTC, iaronaraujo commented on README.md
> +```
```suggestion
```

## Troubleshooting

You can check if others are passing through similar issues [here](https://github.com/vtex-apps/search-page-context/issues). Also, feel free to [open issues](https://github.com/vtex-apps/search-page-context/issues/new) or contribute with pull requests.

## Contributing

Check it out [how to contribute](https://github.com/vtex-apps/awesome-io#contributing) with this project. 

## Tests

To execute our tests go to `react/` folder and run `yarn test`
```

2019-08-30 14:01 UTC, klzns requested changes

2019-08-30 14:01 UTC, klzns commented on react/SearchPageContext.ts
> +const SearchPageStateContext = createContext({})
Move logic of context to here

2019-09-05 21:20 UTC, merged